[package]
name = "taos-query"

edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytes = "1.1"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99"
itertools = "0.10.3"
log = "0.4"
mdsn = { path = "../mdsn", version = "0.2" }
num_enum = "0.5.7"
once_cell = "1.12.0"
parse_duration = "2.1"
rust_decimal = { version = "1", features = ["c-repr"] }
rustversion = "1.0.6"
taos-error = { path = "../taos-error", version = "0.5.12" }
thiserror = "1.0"
url = "2.2.2"
prettytable = "0.10.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.7"

nom = "7"
paste = "1"

async-trait = { version = "0.1.53", optional = true }
futures = { version = "0.3.21", optional = true }

# column
bitflags = "1"
bitvec = "1.0.0"

r2d2 = { version = "0.8.9", optional = true }

tokio = { version = "1", features = ["sync", "rt-multi-thread", "macros", "io-util"] }

[dev-dependencies]
flate2 = "1"
pretty_env_logger = "0.4.0"
rand = "0.8.5"

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = ["r2d2", "async"]
async = ["async-trait", "futures"]
