name: Maturin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PYTHON_VERSION: "3.7" # to build abi3 wheels

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if file changes would trigger a rebuild
        id: rebuild
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/maturin.yml
            taos-ws-py/**
            taos/Cargo.toml
      - uses: actions/setup-python@v4
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          python-version: "3.10"
          architecture: x64

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          target: x86_64
          working-directory: taos-ws-py
          args: --release --strip
      - name: Install built wheel - x86_64
        if: steps.rebuild.outputs.any_changed == 'true'
        run: |
          pip install taos-ws-py --no-index --force-reinstall --find-links target/wheels

      - name: Build wheels - universal2
        uses: PyO3/maturin-action@v1
        with:
          working-directory: taos-ws-py
          args: --release --universal2 --strip
      - name: Install built wheel - universal2
        if: steps.rebuild.outputs.any_changed == 'true'
        run: |
          pip install taos-ws-py --no-index --force-reinstall --find-links target/wheels
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          name: wheels
          path: target/wheels/**

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64] #, x86
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if file changes would trigger a rebuild
        id: rebuild
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/maturin.yml
            taos-ws-py/**
            taos/Cargo.toml
      - uses: actions/setup-python@v4
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          python-version: "3.10"
          architecture: ${{ matrix.target }}

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          target: ${{ matrix.target }}
          working-directory: taos-ws-py
          args: --release --strip

      - name: Install built wheel
        if: steps.rebuild.outputs.any_changed == 'true'
        run: |
          pip install taos-ws-py --no-index --force-reinstall --find-links .\target\wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          name: wheels
          path: target/wheels/**

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if file changes would trigger a rebuild
        id: rebuild
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/maturin.yml
            taos-ws-py/**
            taos/Cargo.toml
      - uses: actions/setup-python@v4
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          python-version: "3.10"
          architecture: x64

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          rust-toolchain: nightly
          target: ${{ matrix.target }}
          working-directory: taos-ws-py
          manylinux: auto
          args: --release --strip

      - name: Install built wheel
        if: matrix.target == 'x86_64' && steps.rebuild.outputs.any_changed == 'true'
        run: |
          pip install taos-ws-py --no-index --force-reinstall --find-links target/wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          name: wheels
          path: target/wheels/**

  linux-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64, armv7]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if file changes would trigger a rebuild
        id: rebuild
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/maturin.yml
            taos-ws-py/**
            taos/Cargo.toml
      - uses: actions/setup-python@v4
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build wheels
        uses: messense/maturin-action@v1
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          target: ${{ matrix.target }}
          rust-toolchain: nightly
          working-directory: taos-ws-py
          manylinux: auto
          args: --release --strip
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Install built wheel
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          arch: ${{ matrix.target }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            apt-get install -y --no-install-recommends python3 python3-pip
            pip3 install -U pip
          run: |
            pip3 install taos-ws-py --no-index --find-links target/wheels/ --force-reinstall
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        if: steps.rebuild.outputs.any_changed == 'true'
        with:
          name: wheels
          path: target/wheels/**
